export enum TASK_STATUS {
  TODO = 'TODO',
  IN_PROGRESS = 'IN PROGRESS',
  DONE = 'DONE',
  ARCHIVED = 'ARCHIVED',
}

export const ERROR_CODE = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
};
